version: '3'
services:
  web:
    env_file:
      - .env
    build: .
    ports:
      - "4883:4883"
    networks:
      - broker-net
    depends_on:
      - redis
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    networks:
      - broker-net
networks:
  broker-net: