version: '3'
services:
  broker:
    env_file:
      - .env
    build: .
    ports:
      - "1883:1883"
    networks:
      - broker-net
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"
    networks:
      - broker-net
networks:
  broker-net:
    name: broker-net
volumes:
  redis-data: