version: '3'
services:
  web:
    env_file:
      - .env
    build: .
    ports:
      - "5000:5000"
    networks:
      - grafana-net
    depends_on:
      - influxdb
      - grafana

  influxdb:
    hostname: influxdb
    env_file:
      - .env
    image: "influxdb:alpine"
    ports:
      - "8086:8086"
    networks:
      - grafana-net

  grafana:
    env_file:
      - .env
    image: "grafana"
    hostname: grafana
    ports:
      - "3000:3000"
    networks:
      - grafana-net
    depends_on:
      - influxdb

networks:
  grafana-net: