version: '3'
services:
  web:
    env_file:
      - .env
    build: .
    ports:
      - "5000:5000"
  influxdb:
    env_file:
      - .env
    image: "influxdb:alpine"
  grafana:
    env_file:
      - .env
      image: "grafana:latest"