version: '3'
services:
  web:
    env_file:
      - .env
    build: .
    ports:
      - "5000:5000"
    networks:
      - grafana-net
      - my-broker-net
    depends_on:
      - influxdb

  influxdb:
    hostname: influxdb
    env_file:
      - .env
    image: "influxdb:alpine"
    ports:
      - "8086:8086"
      - "8083:8083"
    restart: always
    volumes:
      - influxdb-data:/var/lib/influxdb
    networks:
      - grafana-net

  grafana:
    env_file:
      - .env
    image: "grafana/grafana"
    hostname: grafana
    ports:
      - "3000:3000"
    networks:
      - grafana-net
    depends_on:
      - influxdb
      - web

networks:
  grafana-net:
  my-broker-net:
    external:
      name: moscaserver_broker-net
volumes:
  influxdb-data: