version: '3'
services:
  web:
    env_file:
      - .env
    build: .
    ports:
      - "5000:5000"
    networks:
      - grafana-net
    depends_on:
      - influxdb

  influxdb:
    hostname: influxdb
    env_file:
      - .env
    image: "influxdb:alpine"
    ports:
      - "8086:8086"
    restart: always
    volumes:
      - influxdb-data:/var/lib/influxdb
    networks:
      - grafana-net

  grafana:
    env_file:
      - .env
    image: "grafana/grafana"
    hostname: grafana
    ports:
      - "3000:3000"
    networks:
      - grafana-net
    depends_on:
      - influxdb

networks:
  grafana-net:
volumes:
  redis-data: